import type { Metadata } from "next"; // Importing the Metadata type from Next.js
import Link from "next/link";
import "./globals.css"; // Importing global CSS styles

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// RootLayout component that wraps the entire application
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode; // Type definition for children prop
}>) {
  return (
    <html lang="en">
      {/* Setting the language attribute for the HTML document */}
      <body>
        <header className="site-header">
          <nav className="site-nav" aria-label="Main navigation">
            <Link className="site-brand" href="/">
              Mobile Market
            </Link>
            <div className="site-nav__links">
              <Link className="site-nav__link" href="/">
                Home
              </Link>
              <Link className="site-nav__link" href="/product">
                Products
              </Link>
            </div>
          </nav>
        </header>
        <main className="page-shell">
          <div className="page-canvas">{children}</div>
        </main>
      </body>
      {/* Rendering the children components inside the body */}
    </html>
  );
}
